apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kindle-weather
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - weather.example.com
    secretName: weather-tls-cert
  rules:
  - host: weather.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kindle-weather
            port:
              number: 80
