name: Build, Push, Scan and Sign Docker Image
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write 
      id-token: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set short SHA
      run: echo "SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true 
        tags: |
          ghcr.io/${{ github.repository }}/kindle-weather:latest
          ghcr.io/${{ github.repository }}/kindle-weather:${{ env.SHA_SHORT }}
        provenance: true
        sbom: true

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'ghcr.io/${{ github.repository }}/kindle-weather:${{ env.SHA_SHORT }}'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: 'trivy-results.sarif'

    - name: Install cosign
      uses: sigstore/cosign-installer@main

    - name: Sign the published Docker image
      env:
        COSIGN_EXPERIMENTAL: "true"
      run: |
        cosign sign -y ghcr.io/${{ github.repository }}/kindle-weather:${{ env.SHA_SHORT }}
        cosign sign -y ghcr.io/${{ github.repository }}/kindle-weather:latest

    - name: Verify the signed image
      run: |
        cosign verify ghcr.io/${{ github.repository }}/kindle-weather:${{ env.SHA_SHORT }}
        cosign verify ghcr.io/${{ github.repository }}/kindle-weather:latest
